apiVersion: apps/v1
kind: Deployment
metadata: 
  name: deployment-1
spec:
  replicas: 4
  selector:
    matchLabels:
      name: busybox-pod
  template:
    metadata:
      labels:
       name: busybox-pod
    spec:
      containers:
      - name : busybox-container-name
        image: busybox
        command:
        - sh
        - "-c"
        - echo Hello Kubernetes Deployment! && sleep 4600
      